language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
after_success: npm run coverage
deploy:
  branches:
    only:
      - master
  provider: heroku
  app: uno-back
  api_key:
    secure: ${HEROKU_API_KEY}